version: "3.8"

services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=DB_NAME
    ports:
      - '$DB_PORT:$DB_PORT'
    container_name: app_db
    volumes:
      - psql_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379
    container_name: app_redis
  app:
    depends_on:
      - postgresdb
      - redis
    build: .
    restart: always
    env_file: .env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
    links:
      - postgresdb
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local
  psql_data: